### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ajmas** [aalfiann/recachegoose#1]
It would be useful to have Typescript support.

Currently this will generate a type validation error:

```ts
MyModel.findOne({ name: 'blah' }).cache(60)
```

A workaround is:

```ts
(MyModel.findOne({ name: 'blah' }) as any).cache(60)
```

Note, although someone could create a definition via the `@types` package, it would be good to have this as part of the project itself.

I'd propose an `index.d.ts` definition, but at this point I need to work out the right way to go about it.

**Comment by ajmas** [comment]
Maybe we could adapt the one from the following project: https://github.com/xrip/cachegoose as referenced here: https://github.com/boblauer/cachegoose/issues/64

**Comment by aalfiann** [comment]
Yes it will makes this project better if has typescript support, but I'm not familiar with typescript.

Would you like to send a Pull Request to address this issue?

**Comment by piyushbeli** [comment]
It is still not working for me and giving compilation errors. I am on the latest version.

**Comment by aalfiann** [comment]
> It is still not working for me and giving compilation errors. I am on the latest version.

Have you found the solution? would you like to create a PR to fix this?
