### ISSUE TITLE
select not work with cache

### ISSUE THREAD

**Issue by binSaed** [aalfiann/recachegoose#10]
<img width="716" alt="Screenshot 2023-07-03 at 10 38 29 PM" src="https://github.com/aalfiann/recachegoose/assets/33700292/f8fd2ed5-9f8b-4682-823a-28b8489dc787">

**Comment by aalfiann** [comment]
I've found that the `select` queries has not been set as key cache name. see `src/extend-query.js` line 78 - 93.

but, have you tried with giving the key cache name when calling the `cache()`?

for example  
```
User.find(query)
  .sort({createdAt: 1})
  .select(`username gender`)
  .skip(skip)
  .limit(limit)
  .cache(120, 'cachename') // give the key cache name
  exec(function(err, aggResults) {
    ...
  }
```

I'll fix this in the future, but would very happy if someone would create a PR about this issue..
Thanks.

**Comment by aalfiann** [comment]
This issue already solved since this [pull 14](https://github.com/aalfiann/recachegoose/pull/14).
