### ISSUE TITLE
Is it possible to set a max size for the memory cache?

### ISSUE THREAD

**Issue by bartctc** [aalfiann/recachegoose#15]
it looks like this is set at 100 by default by LRUCache, but there doesn't seem to be a way to modify this at the top level

**Comment by aalfiann** [comment]
It seems you're using recachegoose with memory engine.

Yes, you can increase it by adding option count,
  
for example
```js
cachegoose(mongoose, {
  engine: 'memory',
  count: 2000
});
```

adding option count will increase the max size of lru cache.

**Comment by bartctc** [comment]
Hi thanks for the quick response. I am using typescript and I get the following error when trying that

Object literal may only specify known properties, and 'count' does not exist in type 'IOptions'.ts(2353)

Do the types need to be updated to support count as an option?

**Comment by aalfiann** [comment]
ah yes, the types is missing. 
it needs to update.

If you can create the PR it will be faster and helpful.
Thanks.
