### ISSUE TITLE
Cache returning invalid document

### ISSUE THREAD

**Issue by dnish** [aalfiann/recachegoose#6]
Hey,
on some queries, I receive the error, that the <code>save()</code> function isn't defined for the model. We just replaced cache goose with your library. The query looks like this:

```
       user = await this.findOne({_id: visitorId}).cache(300,cacheKey).exec();

      if(user) {
         ....
         user.save();
       }
```

After a while, we get:

```
TypeError: user.save is not a function
```

**Comment by aalfiann** [comment]
Please try to remove `.exec()`

is it works?

**Comment by dnish** [comment]
I'll check it. The confusing thing is that some documents are returned correctly, some of them not. <code>user</code> was always defined, but sometimes it was returned as a function (I've logged typeof user).

**Comment by dnish** [comment]
Removing exec didn't  change anything. I did the following to log the object:

```
 if(!user.save) {
                        console.log(typeof user);
                        console.log(JSON.stringify(user));
                    }
```

It returns an object with the user information, but save method isn't defined, so I guess hydration isn't working correctly? But this happens only on some documents.

**Comment by aalfiann** [comment]
I thought it because 

1. `.exec()` is for callback use., so you don't need to `await`;
2. `findOne` is for query the document, but `save()` is for insert new document.

How about this?
```
 const user = await this.findOne({_id: visitorId}).cache(300,cacheKey);
      if(user) {
       console.log(user)
       }
```

it just weird, cos you want to search document, but you also want to save the document on the same time also there is no object being save in your sample code.

**Comment by dnish** [comment]
Hey,
no, <code>exec()</code> isn't for callback, it returns a promise. The code worked with the old cachegoose before, but we changed because it isn't maintained anymore.

We check with findOne if we already have a user with that specific visitorId. If we have one, we will check when he last visited the page and update his value when the last visit is greater than 30 minutes, that is why we call the save method. 

So basically we are doing the following:

```

 const user = await this.findOne({_id: visitorId}).cache(300,cacheKey).exec(); // Returns a promise
 if(user && user.lastVisit >= CHECK_DATE) {
    user.lastVisit = new Date();
    user.save(); // Here we get the error, that the save method isn't available, which means we don't get a mongoose document returned, instead a raw Javascript object
  }

```

We are getting the same error also on other Models, the only thing that they have in common is that we use the <code>findOne()</code> method, the normal <code>find()</code> method seems to work fine. Maybe it's related with https://github.com/aalfiann/recachegoose/issues/2 ?

**Comment by aalfiann** [comment]
Yes you're right, The cache function not found because the `user` variable will not return as mongoose Model.

Actualy you don't need a cache when you create or update the document. Why you want to cache if the document will going to change? it won't give you a benefit of cache.

So the solution is try to change your code like this

```
const updated = await this.findOneAndUpdate({
    _id: visitorId,
    lastVisit: { $gte: CHECK_DATE }
  }, {
    lastVisit: new Date()
  }, { new: true }).catch(err => {
    return console.log(err);
  });

if (updated) {
  console.log(updated);
};
```
