### ISSUE TITLE
add mongoose ^7.0.0

### ISSUE THREAD

**Issue by OtayNacef** [aalfiann/recachegoose#9]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `recachegoose@9.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/recachegoose/package.json b/node_modules/recachegoose/package.json
index 1e1092f..5b40668 100644
--- a/node_modules/recachegoose/package.json
+++ b/node_modules/recachegoose/package.json
@@ -14,7 +14,7 @@
     "sha1": "^1.1.1"
   },
   "peerDependencies": {
-    "mongoose": "^5.0.1 || ^6.0.0"
+    "mongoose": "^5.0.1 || ^6.0.0 || ^7.0.0"
   },
   "devDependencies": {
     "@babel/cli": "^7.18.10",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by aalfiann** [comment]
Thank you, I have already update to support mongoose 7..
